In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/heart_nb.csv')
df

Age Sex ChestPainType RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA       140          289          0     Normal   
1     49   F           NAP       160          180          0     Normal   
2     37   M           ATA       130          283          0          ?   
3     48   F           ASY       138          214          0          ?   
4     54   M           NAP       150          195          0     Normal   
..   ...  ..           ...       ...          ...        ...        ...   
913   45   M            TA       110          264          0     Normal   
914   68   M           ASY       144          193          1     Normal   
915   57   M           ASY       130          131          0     Normal   
916   57   F           ATA       130          236          0        LVH   
917   38   M           NAP       138          175          0     Normal   

     MaxHR ExerciseAngina  HeartDisease  Oldpeak ST_Slope  
0      172              N             0      0.0       Up  
1      156              N             1      1.0     Flat  
2       98              N             0      0.0       Up  
3      108              Y             1      1.5     Flat  
4      122              N             0      0.0       Up  
..     ...            ...           ...      ...      ...  
913    132              N             1      1.2     Flat  
914    141              N             1      3.4     Flat  
915    115              Y             1      1.2     Flat  
916    174              N             1      0.0     Flat  
917    173              N             0      0.0       Up  

[918 rows x 12 columns]

In [ ]:
df.head()

Age Sex ChestPainType RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA       140          289          0     Normal    172   
1   49   F           NAP       160          180          0     Normal    156   
2   37   M           ATA       130          283          0          ?     98   
3   48   F           ASY       138          214          0          ?    108   
4   54   M           NAP       150          195          0     Normal    122   

  ExerciseAngina  HeartDisease  Oldpeak ST_Slope  
0              N             0      0.0       Up  
1              N             1      1.0     Flat  
2              N             0      0.0       Up  
3              Y             1      1.5     Flat  
4              N             0      0.0       Up

In [ ]:
df.tail()

Age Sex ChestPainType RestingBP  Cholesterol  FastingBS RestingECG  \
913   45   M            TA       110          264          0     Normal   
914   68   M           ASY       144          193          1     Normal   
915   57   M           ASY       130          131          0     Normal   
916   57   F           ATA       130          236          0        LVH   
917   38   M           NAP       138          175          0     Normal   

     MaxHR ExerciseAngina  HeartDisease  Oldpeak ST_Slope  
913    132              N             1      1.2     Flat  
914    141              N             1      3.4     Flat  
915    115              Y             1      1.2     Flat  
916    174              N             1      0.0     Flat  
917    173              N             0      0.0       Up

In [ ]:
df.shape

(918, 12)

In [ ]:
df.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'HeartDisease', 'Oldpeak',
       'ST_Slope'],
      dtype='object')

In [ ]:
df.dtypes

Age                 int64
Sex                object
ChestPainType      object
RestingBP          object
Cholesterol         int64
FastingBS           int64
RestingECG         object
MaxHR               int64
ExerciseAngina     object
HeartDisease        int64
Oldpeak           float64
ST_Slope           object
dtype: object

In [ ]:
#checking for missing values
df.isna().sum()

Age               0
Sex               9
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
HeartDisease      0
Oldpeak           0
ST_Slope          0
dtype: int64

In [ ]:
#handling missing values
df['Sex'].fillna(df['Sex'].mode() [0],inplace=True)
df.isna().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
HeartDisease      0
Oldpeak           0
ST_Slope          0
dtype: int64

In [ ]:
#encoding : changing raw data into a binary format that an algorithm can read and interpret
#technique used: Label Encoding
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df['Sex']=lb.fit_transform(df['Sex'])
df['ChestPainType']=lb.fit_transform(df['ChestPainType'])
df['RestingBP']=lb.fit_transform(df['RestingBP'])
df['RestingECG']=lb.fit_transform(df['RestingECG'])
df['ExerciseAngina']=lb.fit_transform(df['ExerciseAngina'])
df['ST_Slope']=lb.fit_transform(df['ST_Slope'])
df.dtypes

Age                 int64
Sex                 int64
ChestPainType       int64
RestingBP           int64
Cholesterol         int64
FastingBS           int64
RestingECG          int64
MaxHR               int64
ExerciseAngina      int64
HeartDisease        int64
Oldpeak           float64
ST_Slope            int64
dtype: object

In [ ]:
#seperate input and output
y=df.iloc[:,-3].values
y

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,

In [ ]:
df1=df.drop(['HeartDisease'],axis=1)
x=df1.iloc[:,:].values
x

array([[40. ,  1. ,  1. , ...,  0. ,  0. ,  2. ],
       [49. ,  0. ,  2. , ...,  0. ,  1. ,  1. ],
       [37. ,  1. ,  1. , ...,  0. ,  0. ,  2. ],
       ...,
       [57. ,  1. ,  0. , ...,  1. ,  1.2,  1. ],
       [57. ,  0. ,  1. , ...,  0. ,  0. ,  1. ],
       [38. ,  1. ,  2. , ...,  0. ,  0. ,  2. ]])

In [ ]:
#seperate training and testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)
y_test

array([1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0])

In [ ]:
#normalisation : translating data into the range [0, 1] (or any other range) or simply transforming data onto the unit sphere.
#technique used: StandardScaler
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_test

array([[ 0.4923334 ,  0.51843486, -0.82602337, ..., -0.81173563,
         3.31306096, -2.35330018],
       [ 0.27738743,  0.51843486, -0.82602337, ...,  1.23192819,
         1.0653553 , -2.35330018],
       [-0.25997748,  0.51843486, -0.82602337, ...,  1.23192819,
         3.12575215, -0.66523458],
       ...,
       [ 1.45959025,  0.51843486,  2.29955819, ..., -0.81173563,
        -0.80773275, -0.66523458],
       [-0.1525045 ,  0.51843486, -0.82602337, ...,  1.23192819,
         0.59708329, -0.66523458],
       [ 1.56706323,  0.51843486,  1.25769767, ...,  1.23192819,
        -0.80773275,  1.02283103]])

In [ ]:
#Model creation using KNN, Naive Bayes, and SVM
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay,accuracy_score
knn=KNeighborsClassifier(n_neighbors=7)
naivebay=BernoulliNB()
supportvec=SVC()

lst=[knn,naivebay,supportvec]
for i in lst:
  print("*"*100)
  print("Model creation begins")
  print(i)
  i.fit(x_train,y_train)
  print("predicted test result: ")
  y_pred=i.predict(x_test)
  print("confusion matrix")
  print(confusion_matrix(y_test,y_pred))
  print("Accuracy of the model: ")
  print(accuracy_score(y_test,y_pred))


****************************************************************************************************
Model creation begins
KNeighborsClassifier(n_neighbors=7)
predicted test result: 
confusion matrix
[[ 95  14]
 [ 26 141]]
Accuracy of the model: 
0.855072463768116
****************************************************************************************************
Model creation begins
BernoulliNB()
predicted test result: 
confusion matrix
[[ 97  12]
 [ 25 142]]
Accuracy of the model: 
0.8659420289855072
****************************************************************************************************
Model creation begins
SVC()
predicted test result: 
confusion matrix
[[ 97  12]
 [ 21 146]]
Accuracy of the model: 
0.8804347826086957


In [ ]:
#7.	Classification Report
from sklearn.metrics import classification_report
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.82      0.89      0.85       109
           1       0.92      0.87      0.90       167

    accuracy                           0.88       276
   macro avg       0.87      0.88      0.88       276
weighted avg       0.88      0.88      0.88       276

